CREATE TABLE Loans
(
        ID SERIAL PRIMARY KEY,
		SURNAME VARCHAR(30),
        NAME VARCHAR(30),
		PATRONYMIC VARCHAR(30),
		PASSPORT VARCHAR(30),
        STATUS VARCHAR(20),
		LOCATION VARCHAR(100),
		PHONE VARCHAR(20),
        WORK_NAME VARCHAR(100),
		WORK_TIME VARCHAR(100),
		WORK_POSITION VARCHAR(100),
        SUM INTEGER,
		LOAN_TERM INTEGER,
		LOAN_DATE VARCHAR(30),
		APPROVED VARCHAR(20),
		SIGNED VARCHAR(20)
);
